# Generated by Django 3.0.3 on 2020-05-23 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=20, unique=True, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=80, verbose_name='Cliente')),
                ('plano', models.CharField(max_length=20, verbose_name='Plano')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('rua', models.CharField(max_length=100, verbose_name='Rua')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(max_length=40, verbose_name='Bairro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Email_cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Email_Cliente',
                'verbose_name_plural': 'Email_Clientes',
            },
        ),
        migrations.CreateModel(
            name='Email_fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Email_Fornecedor',
                'verbose_name_plural': 'Email_Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Pedido_de_cotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_de_cotacao', models.CharField(max_length=20, verbose_name='Pedido')),
                ('quantidade', models.CharField(max_length=5, verbose_name='quantidade')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Categoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
            options={
                'verbose_name': 'Pedido_de_cotacao',
                'verbose_name_plural': 'Pedidos_de_cotacao',
            },
        ),
        migrations.CreateModel(
            name='Sala_de_leilao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pedido_de_cotacao')),
            ],
            options={
                'verbose_name': 'Sala_de_leilao',
                'verbose_name_plural': 'Salas_de_leilao',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=20, verbose_name='Produto')),
                ('valor_base', models.CharField(max_length=20, verbose_name='Valor Base')),
                ('unidade_medida', models.CharField(max_length=2, verbose_name='Unidade de Medida')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.AddField(
            model_name='pedido_de_cotacao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Produto'),
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(max_length=80, unique=True, verbose_name='Fornecedores')),
                ('razao_social', models.CharField(max_length=40, verbose_name='Razão Social.')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(max_length=15, verbose_name='I.Estadual:')),
                ('categoria', models.CharField(choices=[('Material de Limpeza e Higiene', 'Material de Limpeza e Higiene'), ('Material de Copa', 'Material de Copa'), ('Alimentos em Geral', 'Alimentos em Geral'), ('Frutas e Verduras', 'Frutas e Verduras'), ('Material de Escritório', 'Material de Escritório'), ('Bebidas', 'Bebidas'), ('Descartáveis e Embalagens', 'Descartáveis e Embalagens'), ('Itens de Manutenção Básica', 'Itens de Manutenção Básica')], max_length=100)),
                ('cep', models.CharField(max_length=11, verbose_name='CEP')),
                ('rua', models.CharField(max_length=100, verbose_name='Rua')),
                ('bairro', models.CharField(max_length=30, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=30, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=30, verbose_name='UF')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('telefone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=17, null=True, verbose_name='Celular')),
                ('observacao', models.CharField(blank=True, max_length=400, null=True, verbose_name='Observação')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Email_fornecedor')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Email_cliente'),
        ),
    ]
